version: '3.8'

services:
  flask:
    build: ./
    command: python /app/flask_apps/app.py
    ports:
      - 5000:5000
    volumes:
      - ./flask_apps:/app/flask_apps
    depends_on:
      - redis

  worker:
    build: ./
    command: python /app/flask_apps/worker.py
    volumes:
      - ./flask_apps:/app/flask_apps
    depends_on:
      - redis

  redis:
    image: redis
    ports:
      - 6000:6379